@extends('composant.app')
@section('title','A propos')
@section('content')
<div class="jumbotron ab-jumbotron d-flex flex-column justify-content-center text-center text-white ">
    <h1 class="text-black font-weight-bold"><span class="des">&nbsp</span> A propos</h1>
    <p>Decouvrez les missions et vision de JOBS UAC</p>
</div>   
<div class="container about">
    <p class="text-justify">Sed ut perspiciatis unde omnis iste natus error sit voluptatem ccusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo entore veritatis et quasi architecto beatae vitae dicta  sunt explicabo. Nemo enim ipsam voluptatem quia voluptas aspernit conséquuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi.Sed ut perspiciatis unde omnis iste natus error sit voluptatem ccusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo entore veritatis et quasi architecto beatae vitae dicta  sunt explicabo. Nemo enim ipsam voluptatem quia voluptas aspernit conséquuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi.tempora incidunt ut labore et dolore magnam aliquam quaerat en volim aduptatema. , quis nostrum exercitationem ullam corporis suscipit oriosam, nisi ut aliquid ex ea commodi conséquatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae onséquatur,vel illum qui dolorem eum fugiat quo voluptas nulla ariaturSed ut perspiciatis unde omnis iste natus error tempora incidunt ut labore et dolore magnam aliquam quaerat en volim aduptatema. , quis nostrum exercitationem ullam corporis suscipit oriosam, nisi ut aliquid ex ea commodi conséquatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae onséquatur,vel illum qui dolorem eum fugiat quo voluptas nulla ariaturSed ut perspiciatis unde omnis iste natus error Sed ut perspiciatis unde omnis iste natus error sit voluptatem ccusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo entore veritatis et quasi architecto beatae vitae dicta  sunt explicabo. Nemo enim ipsam voluptatem quia voluptas aspernit conséquuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi.tempora incidunt ut labore et dolore magnam aliquam quaerat en volim aduptatema. , quis nostrum exercitationem ullam corporis suscipit oriosam, nisi ut aliquid ex ea commodi conséquatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae onséquatur,vel illum qui dolorem eum fugiat quo voluptas nulla ariaturSed ut perspiciatis unde omnis iste natus error 
</p>
</div>
    
@endsection